dist: trusty
sudo: required
language: go

go_import_path: github.com/ligato/vpp-agent

git:
  depth: 1
  submodules: false

go:
  - 1.9.x

cache:
  directories:
    - $HOME/build-cache

env:
  - GO_BUILD_TAGS=mockvpp

before_install:
  - make get-linters
  - make get-covtools
  - make get-linkcheck

script:
  - make check-links || true
  - make lint
  - make
  - make test-cover

after_success:
  - goveralls -coverprofile=/tmp/coverage.out -service=travis-ci
