dist: trusty
sudo: required
language: go

go:
  - 1.8.x

cache:
  directories:
- $HOME/build-cache

before_install:
  - go get -v github.com/golang/lint/golint
  - go get github.com/mattn/goveralls
  - sudo ./scripts/build-vpp.sh

script:
  - make lint
  - make
  - make test-cover

after_success:
  - goveralls -coverprofile=/tmp/coverage.out -service=travis-ci
